#!/usr/bin/env python3
"""
Parallel inpainter — companion to mask_and_inpaint.py / mask_and_inpaint_peak.py.

Reads a JSON params file generated by the interactive GUI (which stores the
per-tilt (lo, hi) intensity thresholds), then masks and inpaints every tilt in
parallel using ProcessPoolExecutor.  Designed to run on cluster nodes via SLURM.

Usage
-----
    python inpaint_apply.py --input file.mrc --params file_params.json \\
                            --output file_inpainted.mrc --cpus 16

JSON params format (produced by the GUI's "Save SLURM" button)
---------------------------------------------------------------
    {
      "input":        "/abs/path/to/input.mrc",
      "output":       "/abs/path/to/output.mrc",
      "edge_blend_px": 15,
      "tilts": {
        "0":  {"lo": 40.5,  "hi": 253.0},
        "1":  {"lo": 38.2,  "hi": 248.1},
        ...
      }
    }
"""

import argparse
import json
import multiprocessing
import os
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed

import numpy as np
import numpy.ma as ma
import mrcfile
from scipy.ndimage import label
from tqdm import tqdm

from .smoothn import smoothn


# ---------------------------------------------------------------------------
# Default SLURM template — imported by the GUI scripts
# ---------------------------------------------------------------------------

DEFAULT_SLURM_TEMPLATE = """\
#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={n_cpus}
#SBATCH --mem={mem_gb}G
#SBATCH --time={time}
#SBATCH --output={log_file}

python {script_path} \\
    --input  {input} \\
    --output {output} \\
    --params {params} \\
    --cpus   {n_cpus}
"""


# ---------------------------------------------------------------------------
# Per-tilt worker  (module-level so ProcessPoolExecutor can pickle it)
# ---------------------------------------------------------------------------

def _process_tilt(args: tuple) -> tuple:
    """
    Load one tilt from the mmap'd MRC, mask it, inpaint with smoothn, blend
    the boundary, and return (tilt_idx, result_float32).

    Opening the MRC inside each worker avoids serialising large arrays across
    the process boundary while still allowing concurrent reads (mmap, read-only).
    """
    tilt_idx, input_path, lo, hi, smoothn_workers = args

    # Concurrent read-only mmap access is safe on all major OS/filesystems
    with mrcfile.mmap(input_path, mode='r', permissive=True) as mrc:
        img = np.array(mrc.data[tilt_idx], dtype=float)

    # --- mask: largest connected component inside [lo, hi] ---
    raw = (img >= lo) & (img <= hi)
    if raw.any():
        labeled, n_feat = label(raw)
        if n_feat > 0:
            sizes = np.bincount(labeled.ravel())
            sizes[0] = 0
            mask = (labeled == sizes.argmax()).astype(bool)
        else:
            mask = raw.astype(bool)
    else:
        mask = raw.astype(bool)

    bad = ~mask
    if not bad.any():
        return tilt_idx, img.astype(np.float32)

    # --- inpaint with smoothn ---
    inpainted = smoothn(ma.array(img, mask=bad), s=1e7, max_iter=500,
                        workers=smoothn_workers)

    result = img.copy()
    result[bad] = inpainted[bad]

    # # --- soft edge blend ---
    # dist_inside = distance_transform_edt(mask).astype(float)
    # blend = (dist_inside > 0) & (dist_inside < edge_blend_px)
    # if blend.any():
    #     alpha = np.clip(dist_inside[blend] / edge_blend_px, 0.0, 1.0)
    #     result[blend] = alpha * img[blend] + (1.0 - alpha) * inpainted[blend]

    return tilt_idx, result.astype(np.float32)


# ---------------------------------------------------------------------------
# Main runner
# ---------------------------------------------------------------------------

def run(input_path: str, output_path: str, params: dict,
        n_cpus: int = None, edge_blend_px: int = None,
        smoothn_workers: int = None) -> None:
    """
    Apply per-tilt masks from *params["tilts"]* to *input_path* and write the
    inpainted stack to *output_path*, processing tilts in parallel.
    """
    tilt_params = params["tilts"]
    n_tilts     = len(tilt_params)
    if edge_blend_px is None:
        edge_blend_px = int(params.get("edge_blend_px", 15))
    total_cpus = multiprocessing.cpu_count()
    if n_cpus is None:
        n_cpus = total_cpus
    # Divide remaining CPUs across smoothn's DCT/IDCT threads so tilt processes
    # and FFT threads together use all available cores without oversubscribing.
    if smoothn_workers is None:
        smoothn_workers = max(1, total_cpus // n_cpus)

    print(f"Input           : {input_path}")
    print(f"Output          : {output_path}")
    print(f"Tilts           : {n_tilts}")
    print(f"Tilt workers    : {n_cpus}")
    print(f"smoothn workers : {smoothn_workers}  (DCT threads per tilt)")
    print(f"Blend px        : {edge_blend_px}")

    with mrcfile.mmap(input_path, mode='r', permissive=True) as mrc:
        shape = tuple(mrc.data.shape)

    # Pre-create the output MRC and memory-map it so each tilt is written
    # directly to disk as it finishes — avoids holding the full stack in RAM.
    with mrcfile.new_mmap(output_path, shape=shape, mrc_mode=2,
                          overwrite=True) as out_mrc:
        worker_args = [
            (int(i), input_path,
             float(tilt_params[str(i)]["lo"]),
             float(tilt_params[str(i)]["hi"]),
             smoothn_workers)
            for i in range(n_tilts)
        ]

        with ProcessPoolExecutor(max_workers=n_cpus) as pool:
            futures = {pool.submit(_process_tilt, a): a[0] for a in worker_args}
            for future in tqdm(as_completed(futures), total=n_tilts,
                               desc="Inpainting tilts"):
                tilt_idx, result = future.result()
                out_mrc.data[tilt_idx] = result

    print(f"Saved → {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Parallel MRC inpainter driven by a GUI-produced JSON params file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--input",  required=True,
                        help="Input MRC tilt series")
    parser.add_argument("--output", default=None,
                        help="Output MRC (default: <input>_inpainted.mrc)")
    parser.add_argument("--params", required=True,
                        help="JSON params file from the interactive GUI")
    parser.add_argument("--cpus",   type=int, default=None,
                        help="Tilt-level parallel workers (default: all CPUs)")
    parser.add_argument("--smoothn-workers", type=int, default=None,
                        dest="smoothn_workers",
                        help="DCT threads per tilt inside smoothn "
                             "(default: auto = total_cpus // --cpus)")
    parser.add_argument("--edge-blend", type=int, default=None,
                        dest="edge_blend_px",
                        help="Edge-blend width in pixels (overrides params file value)")
    args = parser.parse_args()

    for path, label_ in [(args.input, "input"), (args.params, "params")]:
        if not os.path.exists(path):
            sys.exit(f"Error: {label_} file not found: {path}")

    output = args.output or os.path.splitext(args.input)[0] + "_inpainted.mrc"

    with open(args.params) as f:
        params = json.load(f)

    run(args.input, output, params,
        n_cpus=args.cpus, edge_blend_px=args.edge_blend_px,
        smoothn_workers=args.smoothn_workers)


if __name__ == "__main__":
    main()
